version: "3.1"

services:
  postgres:
    build: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scraper
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=matthieu.etchegoyen@jestocke.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8080:80

volumes:
  pg-data:
